const{test, expect}=require('@playwright/test');

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
  await page.getByRole('img').click();
  await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
  await page.getByText('Radio Button Example').click();
  await page.locator('label').filter({ hasText: 'Radio1' }).getByRole('radio').check();
  await page.locator('label').filter({ hasText: 'Radio2' }).getByRole('radio').check();
  await page.locator('label').filter({ hasText: 'Radio3' }).getByRole('radio').check();
  await page.getByText('Suggession Class Example').click();
  await page.getByRole('textbox', { name: 'Type to Select Countries' }).click();
  await page.getByRole('textbox', { name: 'Type to Select Countries' }).fill('india');
  await page.locator('#ui-id-44').click();
  await page.getByText('Dropdown Example').click();
  await page.locator('#dropdown-class-example').selectOption('option1');
  await page.locator('#dropdown-class-example').selectOption('option2');
  await page.getByText('Checkbox Example').click();
  await page.locator('#checkBoxOption1').check();
  await page.locator('#checkBoxOption2').check();
  await page.locator('#checkBoxOption3').check();
  await page.locator('#checkBoxOption3').uncheck();
  await page.locator('#checkBoxOption3').uncheck();
  await page.locator('#checkBoxOption1').uncheck();
  await page.getByText('Switch Window Example').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Open Window' }).click();
  const page1 = await page1Promise;
  await page1.getByText('qaclickacademy.com').click();
  await page.getByText('Switch Tab Example').click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Open Tab' }).click();
  const page2 = await page2Promise;
  await page2.getByText('qaclickacademy.com').click();
  await page2.getByRole('link', { name: 'Get This Domain' }).click();
  await page2.getByTestId('domain-search-box-input').click();
  await page.getByText('Switch To Alert Example').click();
  await page.getByRole('textbox', { name: 'Enter Your Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Name' }).fill('sam');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Alert' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Web Table Example').click();
  await page.getByRole('columnheader', { name: 'Instructor' }).click();
  await page.getByRole('columnheader', { name: 'Course' }).click();
  await page.getByRole('columnheader', { name: 'Price' }).click();
  await page.getByRole('cell', { name: 'Selenium Webdriver with Java' }).click();
  await page.getByRole('cell', { name: 'Rahul Shetty' }).first().click();
  await page.getByRole('cell', { name: 'Selenium Webdriver with Java' }).click();
  await page.getByRole('cell', { name: 'Selenium Webdriver with Java' }).click();
  await page.getByRole('cell', { name: '30' }).first().click();
  await page.getByRole('cell', { name: 'Rahul Shetty' }).nth(1).click();
  await page.getByRole('cell', { name: 'Selenium Webdriver with Java' }).click();
  await page.getByRole('cell', { name: 'Learn SQL in Practical +' }).click();
  await page.getByRole('cell', { name: 'Appium (Selenium) - Mobile' }).click();
  await page.getByRole('cell', { name: 'WebSecurity Testing for' }).click();
  await page.getByRole('cell', { name: 'WebServices / REST API' }).click();
  await page.getByText('Element Displayed Example').click();
  await page.getByRole('button', { name: 'Show' }).click();
  await page.getByRole('textbox', { name: 'Hide/Show Example' }).click();
  await page.getByRole('textbox', { name: 'Hide/Show Example' }).fill('ghdfhfghfgh');
  await page.getByRole('button', { name: 'Show' }).click();
  await page.getByRole('button', { name: 'Hide' }).click();
  await page.getByRole('button', { name: 'Show' }).click();
  await page.getByRole('textbox', { name: 'Hide/Show Example' }).click();
  await page.getByRole('button', { name: 'Hide' }).click();
  await page.getByText('Web Table Fixed header').click();
  await page.getByRole('columnheader', { name: 'Name' }).click();
  await page.getByText('Name Position City Amount Alex Engineer Chennai 28 Ben Mechanic Bengaluru 23').click();
  await page.getByRole('columnheader', { name: 'City' }).click();
  await page.getByRole('columnheader', { name: 'Amount' }).click();
  await page.getByRole('cell', { name: 'Engineer' }).first().click();
  await page.getByRole('cell', { name: 'Dwayne' }).click();
  await page.getByText('Name Position City Amount Alex Engineer Chennai 28 Ben Mechanic Bengaluru 23').click();
  await page.getByRole('cell', { name: '33' }).click();
  await page.getByText('Total Amount Collected:').click();
  await page.getByText('Mouse Hover Example').click();
  await page.getByRole('button', { name: 'Mouse Hover' }).click();
  await page.getByRole('link', { name: 'Top' }).click();
  await page.getByText('iFrame Example').click();
  await page.locator('iframe[name="iframe-name"]').contentFrame().getByRole('link', { name: ' Register' }).click();
  await page.locator('iframe[name="iframe-name"]').contentFrame().getByRole('link', { name: ' Login' }).click();
  await page.getByRole('link', { name: 'Social Media' }).click();
  await page.getByRole('link', { name: 'Youtube' }).click();
});